apiVersion: v2
name: backstage-postgresql
description: PostgreSQL database para Backstage - Wrapper del Helm chart de Bitnami
type: application
version: 1.0.0
appVersion: "17.6.0"
dependencies:
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Jaime Henao
    email: jaime.andres.henao.arbelaez@ba.com
