apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Portfolio-jaime/BACKSTAGE-KIND-MIGRATION.git
  username: Portfolio-jaime
  password: ${GITHUB_TOKEN}
