apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-monitoring-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source: Nuestras configuraciones personalizadas (alertas, dashboards)
  source:
    repoURL: https://github.com/Portfolio-jaime/backstage-kind-migration.git
    targetRevision: main
    path: helm-charts/monitoring
    helm:
      releaseName: backstage-monitoring-config

  # Destination
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
