apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy antes que Backstage
spec:
  project: default

  # Source: Nuestro wrapper Helm chart que usa Bitnami PostgreSQL
  source:
    repoURL: https://github.com/Portfolio-jaime/backstage-kind-migration.git
    targetRevision: main
    path: helm-charts/postgresql
    helm:
      releaseName: psql
      # Values desde el repo
      valueFiles:
        - values.yaml

  # Destination
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health check personalizado
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
        - /spec/template/metadata/annotations
