# Default values for backstage
replicaCount: 1

image:
  repository: jaimehenao8126/backstage-production
  pullPolicy: Always
  tag: "v7"

namespace: backstage

service:
  type: ClusterIP
  port: 80
  targetPort: 7007
  sessionAffinity: ClientIP

ingress:
  enabled: true
  className: nginx
  host: backstage.arhean.com
  tls:
    enabled: true
    secretName: backstage-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

postgres:
  enabled: true
  host: psql-postgresql.backstage.svc.cluster.local
  port: 5432
  database: backstage_plugin_catalog
  auth:
    existingSecret: backstage-secrets
    usernameKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD

probes:
  startup:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 12
  liveness:
    initialDelaySeconds: 90
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

monitoring:
  enabled: true
  prometheus:
    scrape: true
    port: 7007
    path: /metrics

env:
  NODE_ENV: production
  NODE_OPTIONS: "--max-old-space-size=1024"

# Environment variables from ConfigMap
envFrom:
  - configMapRef:
      name: backstage-env-config
  - secretRef:
      name: backstage-secrets

# PostgreSQL init container configuration
initContainers:
  enabled: true
  waitForPostgres:
    image: busybox:1.36
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

# Volumes configuration
volumes:
  tmp:
    sizeLimit: 1Gi
  appTmp:
    sizeLimit: 1Gi

# Pod anti-affinity for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - backstage
          topologyKey: kubernetes.io/hostname
