apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 7007
    protocol: TCP
  selector:
    app: backstage
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
