apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source: Helm chart desde repositorio oficial
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.0.0
    helm:
      # Usar values.yaml desde nuestro repositorio
      valueFiles:
        - $values/helm-charts/monitoring/values.yaml

  # Source adicional: nuestro repositorio para values
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 65.0.0
      helm:
        valueFiles:
          - $values/helm-charts/monitoring/values.yaml

    - repoURL: https://github.com/Portfolio-jaime/backstage-kind-migration.git
      targetRevision: main
      ref: values

  # Destination
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
