{{- if not (lookup "v1" "Secret" .Release.Namespace "backstage-postgres-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgres-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgresql
    component: database
type: Opaque
stringData:
  # PostgreSQL admin password
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | default "backstage" | quote }}

  # PostgreSQL user password
  password: {{ .Values.postgresql.auth.password | default "backstage" | quote }}

  # Backstage database connection string
  POSTGRES_HOST: {{ .Release.Name }}-postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_USER: {{ .Values.postgresql.auth.username | default "backstage" | quote }}
{{- end }}
