apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | b64enc }}
